### PR TITLE
Add URI link type and tests

### LINKED ISSUE #33: missing links
It seems that certain links are missed from extraction. They are removed from the text, but not but into links.csv

Example: PMCID: 7856411

Text:
```
Data from this study are publicly available at NeuroVault at NeuroVault (<uri xlink:href="https://neurovault.org/collections/1866/">https://neurovault.org/collections/1866/</uri>).
```
The link does not appear in links.csv, but is removed from the text. Arguably the text in between the `<urI>` tags should not be removed either.

### PR DESCRIPTION
**Pull request by adelavega**
Fixes #33 

- Adds "URI" as a type of tag that can be used to extract links
- Sets links_type to tag type (i.e. `uri`) if this no type found (which happens with the uri tag)
- Modifies test to include example and double number of links expected
- Adds the following (rare but possible) pattern: api preceding image or collection id

### CODE REVIEW

**Comment by jeromedockes** [comment]
thanks a lot @adelavega ! sorry for the late reply. could you run `make format` or `black` or merge the PR I opened on your branch just to make flake8 happy? thanks!
the macos failure looks like an issue with the pandas installation, hopefully it won't show up again

**Comment by jeromedockes** [comment]
actually as it's just automatic formatting I just pushed it directly

**Comment by jeromedockes** [comment]
thanks a lot @adelavega !!
merging

**Comment by adelavega** [comment]
Thank you Jerome!

**Pull request merged**
